### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by fplust** [isamert/scheme.rs#3]
run this line of code in repl：
```scheme
(call-with-input-file "1MB.txt" (lambda (file) (let* ([x (lambda (a b) (lambda (n) (string-append a b n)))] [y (x (read-all file) "a")]) (y "b"))))
```
every time it execute, memory usage increase by 1MB.

**Comment by isamert** [comment]
Unfortunately `scheme.rs` does not have a garbage collector. It's probably not a good idea to use it for long running programs (but for shorter ones, this is a good thing :)). I may implement this in the future*.

*: To be honest it'll probably take years as I can't really find any spare time to work on this.
